# Generated by Django 2.1.2 on 2018-11-08 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        
    ]

    operations = [
        migrations.RenameField(
            model_name='Noticia',
            old_name='decricao',
            new_name='descricao'
        )
    ]
