# Generated by Django 2.1.2 on 2018-11-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='decricao',
            new_name='descricao',
        ),
    ]
