# Generated by Django 2.1.2 on 2018-11-11 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_imageupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(default=datetime.datetime(2018, 11, 11, 19, 29, 26, 766056, tzinfo=utc), upload_to='', verbose_name='Uploaded Image'),
            preserve_default=False,
        ),
    ]
