# Generated by Django 2.1.2 on 2018-11-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='senha',
            field=models.CharField(max_length=6),
        ),
    ]
